-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(100) NOT NULL,
    website character varying(50) NOT NULL,
    phone_number character varying(15) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers_verify
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    email_verification boolean NOT NULL,
    confirmation boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    nationality_id character(11) NOT NULL,
    year_of_birth character(4) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_seekers_verify
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    mernis_verificitation boolean NOT NULL,
    email_verification boolean NOT NULL,
    confirmaton boolean[] NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_titles
(
    id integer NOT NULL,
    title character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_employees
(
    user_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    nationality_id character(11) NOT NULL,
    year_of_birth character(4) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
    email character varying(30) NOT NULL,
    password character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers_verify
    ADD FOREIGN KEY (user_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_seekers_verify
    ADD FOREIGN KEY (user_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.system_employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;